### ISSUE TITLE
Unable to install using pip within Python 3.7.9 environment

### ISSUE THREAD

**Issue by HatedFate** [quantumlib/OpenFermion-PySCF#61]
I am attempting to install this software after running into issues after downloading the pennylane package by following the instructions provided [here](https://pennylane.ai/install.html). When I ran the following:
```
H, qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates)
```

I received the following error: `ModuleNotFoundError: No module named 'openfermionpyscf'`

I decided to install this package manually by going to this repository and using the commands:
```
python -m pip install --user openfermionpyscf
```

But this run into the following issue:
```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

This lead me to install it using the following command:
```
pip install openfermionpyscf
```

This lead to the following error:
```
ERROR: The tar file (C:\Users\13473\AppData\Local\Temp\pip-unpack-ppyy7yj7\pyscf-2.0.1.tar.gz) has a file (C:\Users\13473\AppData\Local\Temp\pip-install-lves2kza\pyscf\pyscf/agf2/aux.py) trying to install outside target directory (C:\Users\13473\AppData\Local\Temp\pip-install-lves2kza\pyscf)
```

This is my first time encountering these types of error messages, so I am not entirely sure what this means or what should be done to resolve it.

**Comment by ElonDormancy** [comment]
I have the same question,Did you have solve this?

**Comment by ncrubin** [comment]
This is a pyscf install problem on what look to be the windows platform.  Try posting this issue there.  I assume you get the same issue when pip installing pyscf.  Right?

**Comment by ncrubin** [comment]
Closing since not strictly an openfermion-pyscf problem

**Comment by ElonDormancy** [comment]
> This is a pyscf install problem on what look to be the windows platform. Try posting this issue there. I assume you get the same issue when pip installing pyscf. Right?

That's true,Pyscf now not support windows platform.
